{
 "title": "Green house dash",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "last_over_time(shelly_greenhouse_temperature[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan 1 state",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "last_over_time(shelly_greenhouse_fan1_output[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan 2 state",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "last_over_time(shelly_greenhouse_fan2_output[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Green house status",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "shelly_greenhouse_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "expr": "shelly_greenhouse_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fan 1 and 2 states",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    { "expr": "shelly_greenhouse_fan1_state", "legendFormat": "__auto" },
    { "expr": "shelly_greenhouse_fan2_state", "legendFormat": "__auto" }
   ]
  }
 ]
}